exports.Messages = {
	// EMAIL_PHONE_REQUIRED : "Email or Phone Number is Required.",
	PASSWORD_REQUIRED: "Password Required",
	NOT_MATCHED: "Password and Confirm password not matched.",
	INVALID_EMAIL_OR_PHONE: "Please provide valid email or phone number",
	EMAIL_REQUIRED: "Email Required.",
	NAME_REQUIRED: "Name Required.",
	TEXT_REQUIRED: "Text Required.",
	PHONE_NUMBER_REQUIRED: "Phone number Required",
	INCORRECT_PASSWORD: "Password is incorrect",
	FIRST_NAME: "FirstName Required",
	INVALID_EMAIL: "Email and password not found",
	_ID_REQUIRED: "_Id Required",
	INVALID_PHONE: "Invalid Phone Number",
	ADMIN_CREATED: "Admin successfully created",
	ADMIN_LOGIN: "Admin login successfully",
	ALREADY_EXIST: "Already exist",
	USER_NOT_FOUND: "User not exist",
	FILE_PROVIDE: "Please select a file",
	VALID_DATA_PROVIDE: "Please provide data",
	ADMIN_DETAILS: "Admin details fetched",
	ADMIN_DELETED: "Admin deleted",
	USER_DETAILS: "User details fetched",
	ADMIN_UPDATE: "Admin details updated",
	USER_UPDATE: "User details updated",
	FORGET_PASSWORD: "OTP sent on your registered mobile number",
	UPLOAD_FILE: "File uploaded",
	RESET_PASSWORD: "Password reset successfully",
	SOMETHING_WENT_WRONG: "Something went wrong",
	USER_SIGNUP: "SignUp successfully",
	USER_SIGNIN: "SignIn successfully",
	EMAIL_ALREADY_EXIST: "Email already exist",
	PHONE_ALREADY_EXIST: "Phone number already exist",
	ESSENTIAL_NUMBER_ADDED: "Essential phone number saved successfully",
	ESSENTIAL_NUMBER_ALREADY: "Essential number already exist",
	UPDATE_ESSENTIAL_NUMBER: "Essential phone number updated successfully",
	GET_ESSENTIAL_NUMBER: "Essential phone number data fetched",
	DELETE_ESSENTIAL_NUMBER: "Essential phone number removed successfully",
	DATA_NOT_FOUND: "Data Not Found",
	CHAPTERS_DATA_NOT_FOUND: "Chapters Data Not Found",
	FILE_UPLOAD_ERROR: "Error while uploading a file",
	SOS_ADDED: "SOS sent successfully",
	SOS_DATA: "SOS fecthed",
	SOS_UPDATED: "SOS updated successfully",
	DOC_NAME_REQUIRED: "Pleas provide document name",
	DOC_ADDED: "Document added successfully",
	DOC_DATA: "My document data fethed",
	INCORRECT_OTP: "OTP is incorrect",
	OTP_REQUIRED: "OTP Required",
	OTP_VERIFIED: "OTP Verified",
	ADD_DISTRICT: "District added",
	GET_DISTRICT: "District Fetched",
	PASSPORT_REQUIRED: "passport Required",
	PERMIT_REQUIRED: "work permit Required",
	REGISTRATION_REQUIRED: "registration book Required",
	MARRIAGE_REQUIRED: "marriage certification Required",
	RESIDENCY_REQUIRED: "residency book Required",
	BIRTH_REQUIRED: "birth certificaton Required",
	MY_DOC_ID: "myDocumentId Required",
	DOC_DATA_LIST: "Document data fetched",
	DOC_DATA_UPDATED: "List of document updated",
	DOC_DATA_DELETED: "Document deleted",
	MESSAGE_ADD: "Message added successfully",
	SOS_MESSAGE_UPDATE: "Sos message updated successfully",
	SOS_MESSAGE_DELETE: "Sos message deleted successfully",
	GET_DATA: "Data Fetched",
	FORM_LINK_REQUIRED: "Form link Required",
	APPLICATION_FORM: "Application form added successfully",
	APPLICATION_FORM_UPDATE: "Application form updated successfully",
	DOC_NOT_FOUND: "Document not found",
	RENEWAL_ALREAY_EXITS: "Renewal already exist",
	RENEWAL_ADD: "Renewal added successfully",
	CUSTOM_DOC_ADD: "Document added successfully",
	DOC_URL_REQUIRED: "docUrl Required",
	NOTIFICATION_TEXT_REQUIRED: "notificationText Required",
	EXPIRY_DATE_REQUIRED: "expiryDate Required",
	ISSUE_DATE_REQUIRED: "issueDate Required",
	OTHER_DESC_REQUIRED: "otherDescription Required",
	REMINDER_REQUIRED: "reminder Required",
	SOS_ID_REQUIRED: "sosMessagesId Required",
	RENEWAL_DATA: "Renewal data fetched",
	ADDRESS_REQUIRED: "Address Required.",
	IMAGE_REQUIRED: "Image Required.",
	STATUS_REQUIRED: "Status Required.",
	LATITUDE_REQUIRED: "latitude Required.",
	LONGITUDE_REQUIRED: "longitude Required.",
	MAP_ADDED: "Address added successfully",
	MAP_UPDATE: "Address updated successfully",
	MAP_DELETE: "Address removed successfully",
	MAP_DATA_FETCHED: "Address data fetched successfully",
	JOB_ADDED: "Job added successfully",
	COMPANY_ADDED: "Company added successfully",
	REVIEW_ADDED: "Review added successfully",
	SALARY_RANGE_REQUIRED: "salary range Required.",
	RATING_REQUIRED: "rating Required.",
	REVIEW_REQUIRED: "review Required.",
	WORK_EXPE_REQUIRED: "work experience Required.",
	EMPLOYMET_TYPE_REQUIRED: "employment type Required.",
	SKILLS_REQUIRED: "skills Required.",
	CANDIDATE_NO_REQUIRED: "candidate no. Required.",
	GET_COMPANY_LIST: "Company list fetched successfully",
	GET_REVIEW_LIST: "Review list fetched successfully",
	TITLE_REQUIRED: "Title Required.",
	COM_ID_REQUIRED: "Company id Required.",
	JOB_DATA: "Job data fetched successfully",
	JOB_DELETE: "Job deleted successfully",
	JOB_UPDATE: "Job updated successfully",
	JOB_SAVED_TO_LIST: "Job saved successfully",
	REMOVE_SAVED_JOB: "Job removed from saved list",
	JOB_ID_REQUIRED: "jobId Required.",
	COMPANY_ID_REQUIRED: "companyId Required.",
	RESUME_REQUIRED: "Resume Required.",
	CITY_REQUIRED: "City Required.",
	COMPANY_NOT_FOUND: "Company Not Found",
	JOB_NOT_FOUND: "Job Not Found",
	APPLIED_DATE_FETCHED: "job applied data fetched",
	JOB_APPLIED: "job applied successfully",
	JOB_ALREADY_EXIST: "job already applied",
	COMPANY_DATA: "company data fetched",
	COMPANY_UPDATE: "company updated",
	USERID_REQUIRED: "userId Required",
	JOB_APPLICATION_UPDATE: "Job application updated successfully",
	REVIEW_UPDATE: "Review updated successfully",
	REVIEW_DELETE: "Review deleted successfully",
	SOS_DELETE: "Sos deleted successfully",
	DEVICE_TOKEN_UPDATE: "device token updated",
	TOKEN_REQUIRED: "Token Required.",
	LIMIT_EXCEED: "You Can't send more than 4",
	NEWS_TITLE_REQUIRED: "newsTitle Required.",
	NEWS_HEADING_REQUIRED: "newsHeading Required.",
	PUBLISH_DATE_REQUIRED: "publishDate Required.",
	NEWS_CONTENT_REQUIRED: "newsContent Required.",
	PUBLISH_BY_REQUIRED: "publishBy Required.",
	TYPE_REQUIRED: "type Required.",
	THUMBNAIL_REQUIRED: "thumbnail Required.",
	NEWS_NOT_FOUND: "News Not Found",
	NEWS_ALREDY_EXIST: "News already exist",
	NEWS_UPDATED: "News updated",
	NEWS_DELETED: "News deleted",
	NEWS_FETCHED: "News data fetched",
	NEWS_ADDED: "News added",
	NEWS_Published: "News Published",
	NEWS_BANNER_UPDATE: "News banner updated",
	NEWS_UnPublished: "News UnPublished",
	NEWS_Priority: "News on Priority",
	NEWS_UnPriority: "News remove from Priority",
	ADD_NEWS_TO_HISTORY: "News added to history",
	VIEW_NEWS_: "News added to view",
	ALREADY_VIEWED: "already viewed",
	NEWS_ID_REQUIRED: "News id Required.",
	ENTERTAINMENT_ID_REQUIRED: "entertainmentId Required.",
	RECNETLY_PLAY_NEWS_FETCHED: "Recently played news data fetched",
	RECNETLY_PLAY_ENTERTAINMENT_FETCHED:
		"Recently played videos and inshorts data fetched",
	VIDEOS_AND_INSHORTS_ADDED: "Videos and Inshorts added",
	SUBTITLE_REQUIRED: "Subtitle Required.",
	CONTENT_REQUIRED: "Content Required.",
	VIDEO_Published: "Video Published",
	VIDEO_unPublished: "Video unPublished",
	VIDEO_ARTICLE_Published: "Video or article published",
	VIDEO_ARTICLE_unPublished: "Video or article unPublished",
	VIDEO_Populars: "video or article added in populars",
	VIDEO_unPopulars: "video or article remove from populars",
	VIDEO_INSHORTS_FETCHED: "Video and inshorts data fetched",
	VIDEO_INSHORTS_UPDATED: "Video and inshorts updated",
	Video_Inshort_DELETED: "Video and inshorts deleted",
	CONTENT_SOURCE_REQUIRED: "Content Source Required.",
	_BANNER_UPDATE: "Banner updated",
	ALL_VIDEOS: "All videos fetched",
	ALL_SHORTS: "All inshorts fetched",
	ALL_POPULAR_VIDEOS: "All videos fetched",
	ALL_POPULAR_ARTICLE: "All articles fetched",
	ALL_VIDEOS_AND_INSHORTS: "All videos and inshorts fetched successfully",
	ALL_VIDEOS_AND_ARTICLES: "All videos and articles fetched successfully",
	ADD_COMMENT: "Comment added",
	COMMENT_FETCHED: "Comment fetched",
	COMMENT_DELETED: "Comment deleted",
	ADD_Views: "video & inshorts added to history",
	ADD_LIKE: "Video liked",
	ADD_UNLIKE: "Video unliked",
	ADD_JOB_SEARCH: "Job search added",
	GET_JOB_SEARCH: "Job search fetched",
	ADD_ENTERTAINMENT_SEARCH: "Entertainment search added",
	GET_ENTERTAINMENT_SEARCH: "Entertainment search fetched",
	ADD_LIVING_SEARCH: "Living search added",
	GET_LIVING_SEARCH: "Living search fetched",
	GET_News_SEARCH: "News search fetched",
	ADD_NEWS_SEARCH: "News search added",
	SOS_LIMIT_UPDATE: "Sos limit updated",
	SOS_LIMIT_ADDED: "Sos limit added",
	LIMIT_EXCEED_USER: "You can not send more than",
	Entertainment_SAVED_LIST: " added to saved list",
	VIDEO_INSHORTS_DATA: "Video and inshorts data fetched",
	JOB_STATUS_UPDATE: "job status updated",
	UPLOAD_PROFILE_PIC: "Profile pic uploaded successfully",
	UPLOAD_DOCUMENT: "Document uploaded",
	PROFILE_PIC_PROVIDE: "Please select a profile pic",
	DOCUMENT_PROVIDE: "Please select a document",
	VIDEO_PROVIDE: "Please select a video",
	UPLOAD_VIDEO: "Video uploaded successfully",
	IMAGE_PROVIDE: "Please select an image",
	UPLOAD_IMAGE: "Image uploaded successfully",
	UPLOAD_THUMBNAIL: "Thumbnail uploaded successfully",
	THUMBNAIL_PROVIDE: "Please select a thumbnail",
	ADD_INDUSTRY_OR_SKILL: " Added",
	CHECK_VALIDATION: "Please provide valid input for type",
	INDUSTRY_SKILLS_DATA: "Industry and skills data fetched",
	SAVED_TO_NEWS_ARTICLE: "News article saved",
	SAVED_TO_NEWS_VIDEO: "News video saved",
	UNSAVED_TO_NEWS_VIDEO: "News video removed from saved list",
	UNSAVED_TO_NEWS_ARTICLE: "News article removed from saved list",
	DOC_UPDATED: "Document updated",
	DOC_DELETED: "Document deleted",
	OFFICE_DATA: "Offices data fetched",
	OFFICE_DATA_UPDATED: "Offices data updated",
	OFFICE_DATA_DELETED: "Offices data deleted",
	VIDEOS_AND_ARTICLE_ADDED: "Videos and Article added",
	VIDEOS_AND_ARTICLE_FETCHED: "Videos and Article fetched",
	VIDEO_ARTICLE_UPDATED: "Video or article updated",
	Video_ARTICLE_DELETED: "Video or article deleted",
	LIVING_ID_REQUIRED: "livingId Required",
	ADD_VIEWS_LIVING: "video & article added to history",
	VIDEOS_AND_ARTICLE_SAVED_DATA: "Videos and Article saved data fetched",
	ADD_VIDEO_OR_ARTICLE: " added",
	REMOVE_VIDEO_OR_ARTICLE: " removed",
	ALL_ARTICLES: "All articles fetched",
	VIDEO_ARTICLE_FETCHED: "Videos and articles data fetched",
	RECNETLY_PLAY_VIDEOS_ARTICLES_FETCHED:
		"Recently played videos and articles data fetched",
	COURSE_NAME_ALREADY_EXIST: "Course already exist with this name",
	COURSE_ADDED: "Course added successfully",
	COURSE_NAME_REQUIRED: "Course name required.",
	COURSE_CONTENT_REQUIRED: "Course content required.",
	COURSE_THUBNAIL_REQUIRED: "Course thubnail required.",
	PUBLISHER_NAME_REQUIRED: "publisher name required.",
	COURSE_CHAPTER_REQUIRED: "Course chapter required.",
	CHAPTER_DATA_FETCHED: "Chapter data fetched",
	CHAPTER_CHAPTERS_DELETED: "Course chapter deleted",
	COURSE_NOT_FOUND: "Course not found",
	COURSE_DETAILS_UPDATED: "Course details updated",
	COURSE_DELETED: "Course deleted",
	COURSE_ID_REQUIRED: "id Required",
	COURSE_CHAPTERS_UPDATED: "Course chapters updated",
	CHAPTER_DETAILS_NOT_FOUND: "Chapter details not found",
	QUIZ_QUESTION_REQUIRED: "Quiz questions required.",
	QUIZ_ANSWER_REQUIRED: "Quiz answers required.",
	QUIZ_ADDED: "Quiz added successfully",
	QUIZ_DELETED: "Quiz deleted successfully",
	QUIZ_UPDATED: "Quiz updated successfully",
	DATA_FETCHED: "Data fetched",
	LIST_OF_POPULAR_COURSES: "List of all popular courses",
	LIST_OF_COURSES_BANNER: "List of all courses banner",
	ADD_Course_SEARCH: "Course search added",
	GET_Course_SEARCH: "Course search fetched",
	COMMENT_REQUIRED: "comment Required.",
	_COURSE_ID_REQUIRED: "Course id Required",
	CHAPTER_ID_REQUIRED: "Chapter id Required",
	COURSE_CHAPTER_NOT_FOUND: "Course chapter not found",
	VIEW_Chapters_: "chapter added to view",
	COURSE_SAVED_TO_LIST: "Course saved successfully",
	REMOVE_SAVED_COURSE: "Course removed from saved list",
	COURSE_SAVED_DATA: "Course saved data fetched",
	ISSAVED_REQUIRED: "isSaved Required",
	quiz_question_id_required: "quizQuestionId Required",
	ANSWER_REQUIRED: "Answer Required",
	QUIZ_QUESTION_NOT_FOUND: "Quiz question not found",
	QUIZ_QUESTION_DELETED: "Quiz question deleted",
	QUIZ_ANSWER_WRONG: "Wrong answer",
	QUIZ_ANSWER_RIGHT: "Rignt answer",
	QUIZ_ANSWER: "Question already answered",
	QUIZ_NOT_FOUND: "Quiz not found",
	QUIZ_NOT_COMPLETED: "Quiz not completed yet",
	QUIZ_COMPLETED: "Quiz completed successfully.",
	COURSE_CHAPTERS_ADDED: "Course chapters added successfully",
	COURSE_ID_REQUIRED_: "courseId Required",
	COMMENT_ID_REQUIRED: "commentId Required.",
	SHOP_NAME_REQUIRED: "Name is required",
	SHOP_EMAIL_REQUIRED: "Email is required",
	SHOP_LOCATION_REQUIRED: "Location is required",
	SHOP_NAME_ALREADY_EXIST: "Shop name already exist",
	SHOP_CREATED: "Shop created sucessfully",
	SHOP_DATA_FETCHED: "Shop data fetched",
	SHOP_DETAILS_NOT_FOUND: "Shop details not found",
	SHOP_NOT_FOUND: "Shop not found",
	SHOP_UPDATED: "Shop updated sucessfully",
	SHOP_ID_REQUIRED: "shopId is required",
	SHOP_DELETED: "Shop deleted sucessfully",
	PRODUCT_NAME_REQUIRED: "Name is required",
	PRODUCT_CATEGORY_REQUIRED: "Category is required",
	PRODUCT_SUBCATEGORY_REQUIRED: "Sub category is required",
	PRODUCT_PRICE_REQUIRED: "Price is required",
	PRODUCT_DISCOUNT_REQUIRED: "Discount is required",
	// PRODUCT_IMAGE_REQUIRED: "Image is required",
	PRODUCT_DESC_REQUIRED: "Description is required",
	PRODUCT_SIZE_REQUIRED: "Size is required",
	PRODUCT_COLOR_REQUIRED: "Color is required",
	PRODUCT_REMAINING_REQUIRED: "remainingIS required",
	PRODUCT_NOT_FOUND: "Product not found",
	PRODUCT_DETAILS_FETCHED: "Product data fetched",
	PRODUCT_UPDATED: "Product updated successfully",
	PRODUCT_DELETED: "Product deleted successfully",
	PRODUCTS_CREATED: "Product created successfully",
	PRODUCT_NAME_ALREADY_EXIST: "Product name already exist",
	PRODUCT_ID_REQUIRED: "productId is required",
	COMMENT_DATA_NOT_FOUND: "Comment Not Found",
	VENDOR_DATA_FETCHED: "Vendors data fetched",
	PRODUCT_ADDED_TO_CART: "Product added to cart successfully",
	CART_DATA_FETCHED: "Cart data fetched",
	CART_DATA_NOT_FOUND: "Cart Data Not Found",
	ALREADY_EXIST_IN_WISHLIST: "Product already in wishlist",
	PRODUCT_ADDED_TO_WISHLIST: "Product added to wishlist",
	SHOP_DATA_NOT_FOUND: "Shop data not found",
	PRODUCT_WISHLIST_FETCHED: "Product wishlist fetched",
};
